apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "chart.fullname" . }}-service-test"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart.name_version" . }}
    app: {{ template "chart.name" . }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: {{ .Values.service.test.image}}
      command: ['curl']
      args: ['-v', '-s', '-X', 'PUT', '{{ template "chart.fullname" . }}:{{ .Values.service.port }}/status']
  restartPolicy: Never
