version: "2.4"
services:
  client:
    image: mockserver/mockserver:integration_testing_client
    networks:
      - test-network
    command:
      - "sleep"
      - "86400"
  mockserver:
    image: mockserver/mockserver:integration_testing
    networks:
      - test-network
    environment:
      MOCKSERVER_LOG_LEVEL: TRACE
      MOCKSERVER_SERVER_PORT: 1234
  mockserver_target:
    image: mockserver/mockserver:integration_testing
    networks:
      - test-network
    environment:
      MOCKSERVER_LOG_LEVEL: TRACE
      MOCKSERVER_SERVER_PORT: 4567

networks:
  test-network:
    driver: bridge